baseURL = 'https://sun.cmama.xyz/'
languageCode = 'en-us'
title = 'sun shines bright'

[markup]
  defaultMarkdownHandler = 'goldmark'

[params]
	author = "computational mama"
  description = "This is aims to be a solar-powered website, which means it sometimes goes offline"