baseURL = "/"
languageCode = 'en-us'
title = 'sun shines bright'

[markup]
[markup.goldmark]
duplicateResourceFiles = false
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
[markup.goldmark.renderHooks]
[markup.goldmark.renderHooks.image]
enableDefault = false
useEmbedded = 'auto'
[markup.goldmark.renderHooks.link]
enableDefault = false
useEmbedded = 'auto'
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[params]
author = "computational mama"
description = "This (WAS) a solar-powered website, which means it sometimes goes offline. It's self-hosted in Zaandam, Netherlands."
homepage = "This website currently documents the setup process and some of the other public projects and experiments run by Computational Mama."

[permalinks]
posts = '/:year/:month/:slugorfilename/'
categories = '/:slug/'

[[menu.main]]
identifier = "why"
name = "Why"
url = "/why/"
weight = 1

[[menu.main]]
identifier = "how"
name = "How"
url = "/how/"
weight = 2

[[menu.main]]
identifier = "resources"
name = "Resources"
url = "/lowtechresources/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
identifier = "ollamasettings"
name = "Ollama Settings"
url = "/ollamasettings/"
weight = 5
